
name: Run Python Script
on: 
  workflow_dispatch:
env:
google_sheets_id: ${{secrets.GOOGLE_SHEETS_TOKEN}}
github_id: ${{secrets.GITHUB_TOKEN}}
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: 
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pandas
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org numpy
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org time
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org base64
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org requests
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org os
          python  !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org google-auth
          python !pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org google-api-python-client
          python conformidade-links-allweb.ipynb
    
    
