
name: Run Python Script
on: 
  push:
    branches: master
  workflow_dispatch:
env:
  google_sheets_id: ${{secrets.GOOGLE_SHEETS_TOKEN}}
  github_id: ${{secrets.GITHUB_TOKEN}}
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          python  -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pandas
          python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org numpy
          python  -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org base64
          python  -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org requests
          python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org os
          python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org google-auth
          python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org google-api-python-client
          python conformidade-links-allweb.py
    
    

